const initialData = {
  tasks: {
    'task-1': { id: 'task-1', content: 'affectionate' },
    'task-2': { id: 'task-2', content: 'engaged' },
    'task-3': { id: 'task-3', content: 'confident' },
    'task-4': { id: 'task-4', content: 'inspired' },
    'task-5': { id: 'task-5', content: 'grateful' },
    'task-6': { id: 'task-6', content: 'peaceful' },
    'task-7': { id: 'task-7', content: 'excited' },
    'task-8': { id: 'task-8', content: 'joyful' },
    'task-9': { id: 'task-9', content: 'happy' },
    'task-10': { id: 'task-10', content: 'refreshed' },
    'task-11': { id: 'task-11', content: 'hopeful' },
    'task-12': { id: 'task-12', content: 'exhilarated' },
    'task-13': { id: 'task-13', content: 'worried' },
    'task-14': { id: 'task-14', content: 'scared' },
    'task-15': { id: 'task-15', content: 'suspicious' },
    'task-16': { id: 'task-16', content: 'annoyed' },
    'task-17': { id: 'task-17', content: 'frustrated' },
    'task-18': { id: 'task-18', content: 'angry' },
    'task-19': { id: 'task-19', content: 'numb' },
    'task-20': { id: 'task-20', content: 'shocked' },
    'task-21': { id: 'task-21', content: 'embarrassed' },
    'task-22': { id: 'task-22', content: 'ashamed' },
    'task-23': { id: 'task-23', content: 'heartbroken' },
    'task-24': { id: 'task-24', content: 'sad' },
    'task-25': { id: 'task-25', content: 'depressed' },
    'task-26': { id: 'task-26', content: 'tense' },
    'task-27': { id: 'task-27', content: 'stressed' },
    'task-28': { id: 'task-28', content: 'vulnerable' },
    'task-29': { id: 'task-29', content: 'fragile' },
    'task-30': { id: 'task-30', content: 'shy' },
    'task-31': { id: 'task-31', content: 'jealous' },
    'task-32': { id: 'task-32', content: 'connection' },
    'task-33': { id: 'task-33', content: 'belonging' },
    'task-34': { id: 'task-34', content: 'community' },
    'task-35': { id: 'task-35', content: 'companionship' },
    'task-36': { id: 'task-36', content: 'consideration' },
    'task-37': { id: 'task-37', content: 'acknowledgement' },
    'task-38': { id: 'task-38', content: 'safety' },
    'task-39': { id: 'task-39', content: 'warmth' },
    'task-40': { id: 'task-40', content: 'air' },
    'task-41': { id: 'task-41', content: 'food' },
    'task-42': { id: 'task-42', content: 'shelter' },
    'task-43': { id: 'task-43', content: 'honesty' },
    'task-44': { id: 'task-44', content: 'authenticity' },
    'task-45': { id: 'task-45', content: 'integrity' },
    'task-46': { id: 'task-46', content: 'play' },
    'task-47': { id: 'task-47', content: 'fun' },
    'task-48': { id: 'task-48', content: 'peace' },
    'task-49': { id: 'task-49', content: 'beauty' },
    'task-50': { id: 'task-50', content: 'equality' },
    'task-51': { id: 'task-51', content: 'inspiration' },
    'task-52': { id: 'task-52', content: 'autonomy' },
    'task-53': { id: 'task-53', content: 'freedom' },
    'task-54': { id: 'task-54', content: 'independence' },
    'task-55': { id: 'task-55', content: 'respect' },
    'task-56': { id: 'task-56', content: 'spontaneity' },
    'task-57': { id: 'task-57', content: 'meaning' },
    'task-58': { id: 'task-58', content: 'discovery' },
    'task-59': { id: 'task-59', content: 'growth' },
    'task-60': { id: 'task-60', content: 'learning' },
    'task-61': { id: 'task-61', content: 'understanding' },
    'task-62': { id: 'task-62', content: 'mourning' },
  },
  needs: {
    'need-1': { id: 'need-1', content: 'connection' },
    'need-2': { id: 'need-2', content: 'belonging' },
    'need-3': { id: 'need-3', content: 'community' },
    'need-4': { id: 'need-4', content: 'companionship' },
    'need-5': { id: 'need-5', content: 'consideration' },
    'need-6': { id: 'need-6', content: 'acknowledgement' },
    'need-7': { id: 'need-7', content: 'safety' },
    'need-8': { id: 'need-8', content: 'warmth' },
    'need-9': { id: 'need-9', content: 'air' },
    'need-10': { id: 'need-10', content: 'food' },
    'need-11': { id: 'need-11', content: 'shelter' },
    'need-12': { id: 'need-12', content: 'honesty' },
    'need-13': { id: 'need-13', content: 'authenticity' },
    'need-14': { id: 'need-14', content: 'integrity' },
    'need-15': { id: 'need-15', content: 'play' },
    'need-16': { id: 'need-16', content: 'fun' },
    'need-17': { id: 'need-17', content: 'peace' },
    'need-18': { id: 'need-18', content: 'beauty' },
    'need-19': { id: 'need-19', content: 'equality' },
    'need-20': { id: 'need-20', content: 'inspiration' },
    'need-21': { id: 'need-21', content: 'autonomy' },
    'need-22': { id: 'need-22', content: 'freedom' },
    'need-23': { id: 'need-23', content: 'independence' },
    'need-24': { id: 'need-24', content: 'respect' },
    'need-25': { id: 'need-25', content: 'spontaneity' },
    'need-26': { id: 'need-26', content: 'meaning' },
    'need-27': { id: 'need-27', content: 'discovery' },
    'need-28': { id: 'need-28', content: 'growth' },
    'need-29': { id: 'need-29', content: 'learning' },
    'need-30': { id: 'need-30', content: 'understanding' },
    'need-31': { id: 'need-31', content: 'mourning' },
  },  
  feels: {
    'feel-1': { id: 'feel-1', content: 'affectionate' },
    'feel-2': { id: 'feel-2', content: 'engaged' },
    'feel-3': { id: 'feel-3', content: 'confident' },
    'feel-4': { id: 'feel-4', content: 'inspired' },
    'feel-5': { id: 'feel-5', content: 'grateful' },
    'feel-6': { id: 'feel-6', content: 'peaceful' },
    'feel-7': { id: 'feel-7', content: 'excited' },
    'feel-8': { id: 'feel-8', content: 'joyful' },
    'feel-9': { id: 'feel-9', content: 'happy' },
    'feel-10': { id: 'feel-10', content: 'refreshed' },
    'feel-11': { id: 'feel-11', content: 'hopeful' },
    'feel-12': { id: 'feel-12', content: 'exhilarated' },
    'feel-13': { id: 'feel-13', content: 'worried' },
    'feel-14': { id: 'feel-14', content: 'scared' },
    'feel-15': { id: 'feel-15', content: 'suspicious' },
    'feel-16': { id: 'feel-16', content: 'annoyed' },
    'feel-17': { id: 'feel-17', content: 'frustrated' },
    'feel-18': { id: 'feel-18', content: 'angry' },
    'feel-19': { id: 'feel-19', content: 'numb' },
    'feel-20': { id: 'feel-20', content: 'shocked' },
    'feel-21': { id: 'feel-21', content: 'embarrassed' },
    'feel-22': { id: 'feel-22', content: 'ashamed' },
    'feel-23': { id: 'feel-23', content: 'heartbroken' },
    'feel-24': { id: 'feel-24', content: 'sad' },
    'feel-25': { id: 'feel-25', content: 'depressed' },
    'feel-26': { id: 'feel-26', content: 'tense' },
    'feel-27': { id: 'feel-27', content: 'stressed' },
    'feel-28': { id: 'feel-28', content: 'vulnerable' },
    'feel-29': { id: 'feel-29', content: 'fragile' },
    'feel-30': { id: 'feel-30', content: 'shy' },
    'feel-31': { id: 'feel-31', content: 'jealous' },
  },  
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Possible Feelings',
      taskIds: ['task-1', 	'task-2', 	'task-3', 	'task-4', 	'task-5', 	'task-6', 	'task-7', 	'task-8', 	'task-9', 	'task-10', 	'task-11', 	'task-12', 	'task-13', 	'task-14', 	'task-15', 	'task-16', 	'task-17', 	'task-18', 	'task-19', 	'task-20', 	'task-21', 	'task-22', 	'task-23', 	'task-24', 	'task-25', 	'task-26', 	'task-27', 	'task-28', 	'task-29', 	'task-30', 	'task-31'],
    },
    'column-2': {
      id: 'column-2',
      title: 'Maybe I Feel?',
      taskIds: [],
    },
    'column-3': {
      id: 'column-3',
      title: 'I Feel',
      taskIds: [],
    },
    'column-4': {
      id: 'column-4',
      title: 'Possible Needs',
      taskIds: [	'task-32',	'task-33',	'task-34',	'task-35',	'task-36',	'task-37',	'task-38',	'task-39',	'task-40',	'task-41',	'task-42',	'task-43',	'task-44',	'task-45',	'task-46',	'task-47',	'task-48',	'task-49',	'task-50',	'task-51',	'task-52',	'task-53',	'task-54',	'task-55',	'task-56',	'task-57',	'task-58',	'task-59',	'task-60',	'task-61',	'task-62'],
    },
    'column-5': {
      id: 'column-5',
      title: 'Maybe I Need?',
      taskIds: [],
    },
    'column-6': {
      id: 'column-6',
      title: 'I Need',
      taskIds: [],
    },
  },
  // Facilitate reordering of the columns
  columnOrder: ['column-1', 'column-2', 'column-3'],
  columnOrder2: ['column-4', 'column-5', 'column-6'],
};

export default initialData;
